fail_fast: false

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.29.5
    hooks:
      - id: typos
        pass_filenames: false

  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: generate-json-schema
        name: generate json schema
        entry: cargo run -- generate-json-schema
        language: system
        types: [rust]
        pass_filenames: false

ci:
  skip: [clippy, rustfmt, generate-json-schema]
